replicaCount: 2

image:
  repository: richiesuazo/multi-region-aks-webapp-new
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

serviceAccount:
  create: false
  name: ""